### ISSUE TITLE
Launching a ROM sends me back to ES, on Win10 64 bit

### ISSUE THREAD

**Issue by josephrooks** [Francommit/win10_emulation_station#28]
As the title says, I'm running into an issue getting ES to actually launch any games. It's just showing my desktop for a second, and then returning right back to the game list in Emulation Station.

I'm running a 64 bit version of  Windows 10, so not sure what the issue could be.

**Comment by Francommit** [comment]
That usually means your emulator or rom isn't working correctly. What are
you trying to run?

**Comment by josephrooks** [comment]
I tried running several GBA and GBC games that are working fine in other emulators. Also verified that they'd launch using the version of RetroArch that was installed, and when launching them from within RetroArch directly they do work.

**Comment by Francommit** [comment]
Do any of the games included work at all, or is it specific rooms
separately supplied...?

**Comment by NewAgeRipper** [comment]
**Not sure about anyone else but the scripts get to a good start and then displays this.**

Start-BitsTransfer : The server did not return the file size. The URL might point to dynamic content. The               Content-Length header is not available in the server's HTTP reply.                                                      At C:\Users\secre\Desktop\PRElias-win10_emulation_station-2a81821\prepare.ps1:44 char:9                                 +         Start-BitsTransfer -Source $url -Destination $output                                                          +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                              + CategoryInfo          : InvalidOperation: (:) [Start-BitsTransfer], Exception                                         + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.BackgroundIntelligentTransfer.Management.NewBits     TransferCommand                                                                                                                                                                                                                              RetroArch.7z does not exist...Downloading.                                                                              Start-BitsTransfer : HTTP status 404: The requested URL does not exist on the server.                                   At C:\Users\secre\Desktop\PRElias-win10_emulation_station-2a81821\prepare.ps1:44 char:9                                 +         Start-BitsTransfer -Source $url -Destination $output                                                          +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                              + CategoryInfo          : InvalidOperation: (:) [Start-BitsTransfer], Exception                                         + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.BackgroundIntelligentTransfer.Management.NewBits
   TransferCommand


**Things go good for a bit and then another one.**

System ERROR:                                                                                                           The system cannot find the file specified.                                                                              Rename-Item : Cannot rename because item at 'C:\Users\secre\.emulationstation\systems\PCSX2 1.4.0\' does not exist.     At C:\Users\secre\Desktop\PRElias-win10_emulation_station-2a81821\prepare.ps1:173 char:1                                + Rename-Item -Path $ps2ExtractedPath -NewName "pcsx2"                                                                  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                      + CategoryInfo          : InvalidOperation: (:) [Rename-Item], PSInvalidOperationException                              + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.RenameItemCommand


**And then I get one more error.**

& : The term 'C:\Users\secre\.emulationstation\systems\retroarch\retroarch.exe' is not recognized as the name of a      cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify   that the path is correct and try again.                                                                                 At C:\Users\secre\Desktop\PRElias-win10_emulation_station-2a81821\prepare.ps1:186 char:3                                + & $retroarchExecutable
+   ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\secre\...h\retroarch.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**After which all you see happening after is.....**

Checking for config file...
Checking for config file...
Checking for config file...
Checking for config file...
Checking for config file...
Checking for config file...
Checking for config file...
Checking for config file...
Checking for config file...
Checking for config file...

**Comment by PRElias** [comment]
Hi @josephrooks I think that the best solution is to start again on another folder and trying to start the script by navigating to the folder on console.

Looks like a problem on locating the files by the script then wrong paths are saved on the configurations file

**Comment by Francommit** [comment]
Any further news? Otherwise I'm going to close this isuse.

**Comment by ghost** [comment]
I'm having the same issue,  When I try to play a rom, the screen flickers black and back to rom selection screen.  This is what the log shows.

May 15 18:20:39 lvl2: 		C:\Users\***\.emulationstation\systems\retroarch\retroarch.exe -L C:\Users\***\.emulationstation\systems\retroarch\cores\fceumm_libretro.dll "C:\Users\***\.emulationstation\roms\nes\Arkanoid (USA).nes"
May 15 18:20:39 lvl1: 	...launch terminated with nonzero exit code 1!

**Comment by ghost** [comment]
the last line is the problem, disregard the rest I replaced my name with ***

**Comment by Francommit** [comment]
Hey JoeP24,

Could you uninstall EmulationStation, remove everything you previously downloaded and run the 'one liner' command on the main page.

I've made a few changes and I've tested each game and it works locally when the only thing I do from a clean slate is run the above command.

**Comment by ghost** [comment]
Hi Francommit, thanks for the help.  I did a clean install as you suggested.  Install worked perfectly but still get same issue.  Pick a rom, fade to black, back to rom selection screen.  Could it be that my user folder consists of my full name with a space in between?

May 16 11:00:32 lvl2: 	Attempting to launch game...
May 16 11:00:32 lvl2: 	getting volume as 100 ( from float 1)
May 16 11:00:32 lvl2:       C:\Users\first last\.emulationstation\systems\retroarch\\retroarch.exe -L C:\Users\first last\.emulationstation\systems\retroarch\\cores\fbalpha2012_libretro.dll "C:\Users\first last\.emulationstation\roms\ngp\Metal Slug - 1st Mission (World) (En,Ja).ngc"
May 16 11:00:32 lvl1: 	...launch terminated with nonzero exit code 1!

**Comment by PRElias** [comment]
It could be because of the change on fbneo name on retroarch. It needs more investigation, but I had this problem on the past.

It happens on all system for you @JoeP24 ?

**Comment by ghost** [comment]
Yes @PRElias

**Comment by Francommit** [comment]
Ahh what rom are you trying to load? That's a retroarch problem.
I just had the same problem when adding a NeoGeoPocket ROM.

Will need to grab another core I suspect and change the template for others.

**Comment by ghost** [comment]
same issue, all roms for all systems.  So definitely something on my end.

**Comment by ghost** [comment]
Do I need to do anything besides run one liner and then put ROMs in respective folders? I see the cores folder on my desktop too, does anything need to be put in there? Very new to this all.

**Comment by ghost** [comment]
Click on rom
ES fades away
cmd window opens and closes immediately
ES fades back in
This happens for all systems all roms

**Comment by Francommit** [comment]
Hey Joe,

I've done a bunch of work.
Could you grab a new copy and try again?

Thanks

**Comment by ghost** [comment]
Thank you Chris,

I was able to come up with a work around. I had to create another user in Win10 with admin privileges and then the one liner ran without a problem and ES is working fine.  The problem seems to be that my normal account has a space in the user name.  Even with all the online research and trying every combo of inserting quotes in the commands in the system cfg file nothing worked at all.  But thank you, I will do another clean install with your updated one liner when I get a chance.

**Comment by josephrooks** [comment]
I'll try it out again with the update too, just grabbed a copy and put it into my "stuff I need to install" folder. (Hi other Joe!)

**Comment by Francommit** [comment]
Have you guys managed to get around to trying again?

**Comment by Francommit** [comment]
Hey @JoeP24  and @josephrooks , had a chance to try it out again?

**Comment by josephrooks** [comment]
Haven't revisited, have been drowning in work too much to do any tinkering. Feel free to close this issue unless you'd like to wait and see if someone else can confirm it's fixed.

**Comment by Francommit** [comment]
Done a bunch more work and tested it on a few systems, LMK if it persists.
