### ISSUE TITLE
jrassa Build of EmulationStation is Crashy

### ISSUE THREAD

**Issue by stephenegriffin** [Francommit/win10_emulation_station#8]
As referenced in #5, I was getting a bum build of Emulationstation that I could fix by wiping ES and reinstalling from emulationstation.org. Odd thing was choco should be the same exact build.

I tracked the problem down to step 11, where the continuous integration build from @jrassa's GitHub is laid over top of the choco build. This build crashes for me. I dunno why, but the crash is in the ES binary itself, not in a call to another binary. BTW, this build is several months old - it looks like CI isn't functioning. A more current build may not have this problem.

I propose we remove step 11, or give a command line switch until we can figure out why the jrassa build is problematic.

**Comment by Francommit** [comment]
Sounds good. I'm happy to tackle this over the weekend or during the week when I have some spare time! Thanks for your efforts!

**Comment by jrassa** [comment]
FYI, despite the date that shows up on Github, the CI builds are still being updated.  It is just that the integration between Appveyor and Github doesn't update the build date and revision.  I am looking into ways to get this to update properly since I occasionally get questions about it.

As for the crash, it may be due to a recent code change.  There was a change recently that changed how required resources were included with ES.  Previously these required resources were embedded into the exe.  Now they are kept in a separate directory to allow users to further customize ES by replacing them.  There should be a `resources` directory included in the the downloads.  Make sure that this directory is copied to the install directory as well.

There were some reports on the RetroPie forums that it still wasn't launching unless using the scripts from [Portable EmulationStation](https://github.com/HerbFargus/Portable-Game-Station/wiki/Portable-Emulationstation).  I just tested the latest build and that is what I am seeing as well.  The only thing the scripts do is set an environment variable name `HOME ` to the current directory.  I did a quick test and I was able to get it to launch by setting the `HOME` in my global environment variables to point to `C:\Users\<username>`.

**Comment by Francommit** [comment]
Two things to do then:

1.) Ensure the 'resources' folder is being moved across.
2.) Set PS to add in a HOME variable
3.) Test

Thanks for the reply jrassa!

**Comment by jrassa** [comment]
I have an idea about why it is crashing if HOME is not set.  Hopefully it can be corrected.

**Comment by stephenegriffin** [comment]
We may also wanna reconsider why we use Choco at all if we’re just gonna replace it.

**Comment by Francommit** [comment]
My initial choice to use the chocolatey installer was to force people to already setup and emulation-station required libraries as well as putting it in the correct location. I think simply using the force flag and setting the environment variable will make most problems go away. 

At this stage we can potentially remove it, just means more work for us down the line. I think I also used it to run it initially to correctly generate a XML file that I was manually changing later on in the script.

Happy to change anything though if you think one ways better than another!

**Comment by stephenegriffin** [comment]
Looks like the crash has been fixed - we can integrate from https://github.com/jrassa/EmulationStation/releases/tag/continuous-master

**Comment by jrassa** [comment]
I can confirm that the crash has been fixed and there should be no need to set the HOME variable.

Regarding the release.  I made some changes to the build process so that the release shows the correct date/revision.  The name has also changed to `continuous-master`.  There will also be a `continuous-stable` release.  In RetroPie's repository we use master for the latest changes and those changes are then pushed to stable after they have been more thoroughly tested.
