### ISSUE TITLE
Write-ChocolateySuccess is deprecated

### ISSUE THREAD

**Issue by DasKatzchen** [Francommit/win10_emulation_station#9]
Got this message while using your script. Figured you should know about it. Full message is:
`WARNING: Write-ChocolateySuccess is deprecated and will be removed in v2. If you are the maintainer, please remove it from your package file.` It was right after installing directx.

**Comment by Francommit** [comment]
Hey DieKatzchen,

This is code that exists within the directx chocolatey package.
This will have to be fixed by the dev of that chocolatey package themselves.

Usually two different scenarios happen in this case.

1.) The original dev disappears and the resulting chocolatey package becomes useless, where the community will use a different but similiary named package to meet the requirement of installing directx.

2.) They'll fix it and everything will continue to run smoothly.

Thanks for pointing it out though!

**Comment by DasKatzchen** [comment]
I had a suspicion it was upstream.
